// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

function malloc(x) {
  return {
          contents: x
        };
}

var p = {
  contents: 42
};

var Segfault = /* @__PURE__ */Caml_exceptions.create("Pointers.Segfault");

function deref(ptr) {
  if (ptr !== undefined) {
    return ptr.contents;
  }
  throw {
        RE_EXN_ID: Segfault,
        Error: new Error()
      };
}

function assign(ptr, x) {
  if (ptr !== undefined) {
    ptr.contents = x;
    return ;
  }
  throw {
        RE_EXN_ID: Segfault,
        Error: new Error()
      };
}

console.log(deref(p));

assign(p, 2);

console.log(deref(p));

var $$null;

exports.$$null = $$null;
exports.malloc = malloc;
exports.p = p;
exports.Segfault = Segfault;
exports.deref = deref;
exports.assign = assign;
/*  Not a pure module */
