// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

var fact0 = {
  contents: (function (x) {
      return x + 0 | 0;
    })
};

function fact(n) {
  if (n === 0) {
    return 1;
  } else {
    return Math.imul(n, Curry._1(fact0.contents, n - 1 | 0));
  }
}

fact0.contents = fact;

console.log(fact(5));

exports.fact0 = fact0;
exports.fact = fact;
/*  Not a pure module */
