// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var r = {
  contents: 5
};

console.log(r.contents);

r.contents = 32;

console.log(r.contents);

exports.r = r;
/*  Not a pure module */
