// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function $$return(x) {
  return [
          x,
          ""
        ];
}

function bind(m, f) {
  var match = Curry._1(f, m[0]);
  return [
          match[0],
          m[1] + match[1]
        ];
}

var Writer = {
  $$return: $$return,
  bind: bind
};

function inc(x) {
  return x + 1 | 0;
}

function dec(x) {
  return x - 1 | 0;
}

function log(name, f, x) {
  return [
          Curry._1(f, x),
          "Called " + name + " on " + String(x)
        ];
}

function loggable(name, f, x, s1) {
  var match = log(name, f, x);
  return [
          match[0],
          s1 + match[1]
        ];
}

function loggable_inc(param, param$1) {
  return loggable("inc", inc, param, param$1);
}

function loggable_dec(param, param$1) {
  return loggable("dec", dec, param, param$1);
}

function make(x) {
  return [
          x,
          ""
        ];
}

function bind$1(m, f) {
  var match = Curry._1(f, m[0]);
  return [
          match[0],
          m[1] + match[1]
        ];
}

function compose(f, g, x, x$1) {
  return bind$1(Curry._1(f, x$1), Curry.__1(g));
}

exports.Writer = Writer;
exports.inc = inc;
exports.dec = dec;
exports.log = log;
exports.loggable = loggable;
exports.loggable_inc = loggable_inc;
exports.loggable_dec = loggable_dec;
exports.make = make;
exports.bind = bind$1;
exports.compose = compose;
/* No side effect */
